languageCode = "en"
languageName = "English"
weight = 1
title = "Matt's landing page"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-06"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Mattis Swannet"
  image = "img/pfp_square.jpg"
  headline = "Technology and geography enthusiast."
  bio = "IT student at KdG Antwerp, specializing in Systems & Network-management"
  links = [
    { email = "mailto:mattisswannet@gmail.com" },
    { github = "https://github.com/matt-kowalski" },
    { youtube = "https://www.youtube.com/channel/UCqae5yZAOoLqlbZ98SlFAxQ" },
  ]